# Netlify Configuration for IdeaFlux

[build]
  # Build settings
  publish = "."
  command = "echo 'Static site - no build required'"

# Redirect rules
[[redirects]]
  # SPA fallback for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff2"

# Environment variables
[context.production.environment]
  NODE_ENV = "production"

# Form handling
[forms]
  [forms.contact]
    name = "contact-form"
    
# Functions (for future API endpoints)
[functions]
  directory = "netlify/functions"

# Edge functions
[[edge_functions]]
  function = "geolocation"
  path = "/*"

# Branch deploys
[context.branch-deploy]
  command = "echo 'Branch deploy'"

[context.deploy-preview]
  command = "echo 'Deploy preview'"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "netlify-plugin-minify-html"
  [plugins.inputs]
    contexts = ["production"]

# PWA settings
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=31536000"

# API rate limiting
[[edge_functions]]
  function = "rate-limit"
  path = "/api/*"