# Netlify Configuration for IdeaFlux - Simplified Version
# هذا إعداد مبسط لتجنب مشاكل البلاجين

[build]
  publish = "."
  command = "echo 'IdeaFlux - Simple Build Complete'"

# Basic Headers Only
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# HTML Files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Static Assets
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "application/javascript; charset=utf-8"

# Basic Redirects
[[redirects]]
  from = "/canvas"
  to = "/canvas.html"
  status = 200

[[redirects]]
  from = "/workspace"
  to = "/canvas.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/canvas.html"
  status = 200

# SPA Fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment
[context.production.environment]
  NODE_ENV = "production"
  GOOGLE_AI_API = "AIzaSyByEXNDlu9kNaxJWxm7mxxe5vmAqe98DpE"
  APP_VERSION = "2.0.0"